from abc import ABC, abstractmethod
from typing import Dict, Any, Optional


class BaseCommitParser(ABC):
    """
    Abstract Base Class for all commit parsers.
    Subclasses must implement the `parse` method to convert a commit's raw textual 
    and structural data into a Knowledge Graph-friendly dictionary format.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Optional initialization for parser-specific rules, thresholds, 
        or tree-sitter language mappings.
        """
        self.config = config or {}

    @abstractmethod
    def parse(self, commit_payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Parses a single commit payload and returns extracted structural elements.

        Args:
            commit_payload: A dictionary containing 'message', 'diff', 'project', etc.
                            (as generated by CommitDataLoader).

        Returns:
            A dictionary representing extracted entities, relations, or features 
            destined for the Knowledge Graph.
        """
        pass


class SimpleTextCommitParser(BaseCommitParser):
    """
    A baseline parser implementation that acts as a placeholder or 
    basic keyword extractor before we build complex AST engines.
    """

    def parse(self, commit_payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Concrete implementation of the baseline parser.
        """
        message = commit_payload.get("message", "")
        diff = commit_payload.get("diff", "")
        
        # Placeholder dictionary for future KG triple extractions
        extracted_info = {
            "commit_id": commit_payload.get("commit_id"),
            "entities": [],
            "relations": [],
            "metadata_features": {
                "message_length": len(message),
                "has_fix_keywords": any(kw in message.lower() for kw in ["fix", "bug", "issue", "close"])
            }
        }
        
        # Your future extraction logic goes here
        # e.g., self._extract_modified_methods(diff)
        
        return extracted_info