#!/usr/bin/env python3
"""Inject Family 7 (Program Slicing) cells into base_structure_analysis.ipynb."""
import json
from pathlib import Path

nb_path = Path('experiments/notebooks/base_structure_analysis.ipynb')
nb = json.loads(nb_path.read_text(encoding='utf-8'))


def md(cell_id, lines):
    return {'cell_type': 'markdown', 'id': cell_id, 'metadata': {},
            'source': lines}


def code(cell_id, lines):
    return {'cell_type': 'code', 'id': cell_id, 'metadata': {},
            'execution_count': None, 'outputs': [], 'source': lines}


new_cells = [

    md('a700b001', [
        '## Family 7 — Program Slicing\n',
        '\n',
        '**Program slices** capture which statements influence (backward slice) '
        'or are influenced by (forward slice) a given criterion statement, via '
        'the Program Dependence Graph (PDG) built in Family 5.\n',
        '\n',
        'A *backward slice* on criterion $c$ is the set of statements that may '
        'affect the value computed at $c$ — reached by following dependence '
        'in-edges (CDG \\u222a DDG) backward. '
        'A *forward slice* on $c$ gives all statements $c$ can transitionally '
        'influence.\n',
        '\n',
        'Key scalar features per method:\n',
        '- `max_backward_slice` / `mean_backward_slice`\n',
        '- `max_forward_slice` / `mean_forward_slice`\n',
        '- `return_slice_size` — backward slice of the return/throw criterion\n',
        '- `slice_coverage` — max backward slice / n_statements\n',
        '- `mean_slice_coverage` — average fraction across all criteria\n',
        '\n',
        'Run once to generate outputs:  \n',
        '```\n',
        'python build_slice_features.py\n',
        '```',
    ]),

    code('a700b002', [
        'from pathlib import Path\n',
        'import json, pickle\n',
        'import numpy as np\n',
        'import matplotlib.pyplot as plt\n',
        'import networkx as nx\n',
        'from collections import Counter, defaultdict\n',
        '\n',
        'OUT7 = Path(PROJECT_ROOT) / "outputs"\n',
        'EX7  = OUT7 / "slice_example_graphs"\n',
        '\n',
        'with open(OUT7 / "slice_rows.json", encoding="utf-8") as f:\n',
        '    slice_rows = json.load(f)\n',
        'with open(OUT7 / "slice_aggregates.json", encoding="utf-8") as f:\n',
        '    slice_agg = json.load(f)\n',
        '\n',
        'print(f"Methods loaded : {len(slice_rows)}")\n',
        'print(f"Files OK       : {slice_agg[\'ok_files\']}")\n',
        'print(f"Files skipped  : {len(slice_agg[\'skipped_files\'])}")\n',
    ]),

    code('a700b003', [
        '# Summary statistics\n',
        'mb  = [r["max_backward_slice"]  for r in slice_rows]\n',
        'mf  = [r["max_forward_slice"]   for r in slice_rows]\n',
        'sc  = [r["slice_coverage"]      for r in slice_rows]\n',
        'rs  = [r["return_slice_size"]   for r in slice_rows]\n',
        'nde = [r["n_dep_edges"]         for r in slice_rows]\n',
        '\n',
        'def pct(vals, p): return sorted(vals)[int(len(vals)*p/100)]\n',
        '\n',
        'print("Max backward slice  min=%d  p25=%d  med=%d  p75=%d  p90=%d  max=%d"\n',
        '      % (min(mb), pct(mb,25), pct(mb,50), pct(mb,75), pct(mb,90), max(mb)))\n',
        'print("Max forward  slice  min=%d  p25=%d  med=%d  p75=%d  p90=%d  max=%d"\n',
        '      % (min(mf), pct(mf,25), pct(mf,50), pct(mf,75), pct(mf,90), max(mf)))\n',
        'print("Slice coverage(max) min=%.2f p25=%.2f med=%.2f p75=%.2f max=%.2f"\n',
        '      % (min(sc), pct(sc,25), pct(sc,50), pct(sc,75), max(sc)))\n',
        'print("Return slice size   mean=%.1f  max=%d" % (sum(rs)/len(rs), max(rs)))\n',
        'print("Dependence edges    mean=%.1f  max=%d" % (sum(nde)/len(nde), max(nde)))\n',
        '\n',
        'n_trivial = sum(1 for v in mb if v <= 1)\n',
        'print(f"\\nMethods with max backward-slice <= 1 (trivial): {n_trivial}/{len(mb)} = {n_trivial/len(mb):.1%}")\n',
        'n_hi_fwd = sum(1 for r in slice_rows\n',
        '               if r["max_forward_slice"] / max(1, r["n_stmt_nodes"]) > 0.5)\n',
        'print(f"Methods where one stmt forward-slices >50% of body: "\n',
        '      f"{n_hi_fwd}/{len(slice_rows)} = {n_hi_fwd/len(slice_rows):.1%}")\n',
    ]),

    code('a700b004', [
        '# Fig 1: backward-slice size distribution, slice coverage, backward vs forward\n',
        'fig, axes = plt.subplots(1, 3, figsize=(14, 4))\n',
        '\n',
        'bvals = slice_agg["bsize_sample"]\n',
        'ax = axes[0]\n',
        'ax.hist(bvals, bins=min(60, max(bvals)+1), color="#4472C4",\n',
        '        edgecolor="white", linewidth=.3)\n',
        'ax.set_xlabel("Backward-slice size (statements)")\n',
        'ax.set_ylabel("Count")\n',
        'ax.set_title("Backward Slice Size Distribution")\n',
        'ax.axvline(np.median(bvals), color="red", linestyle="--", linewidth=1.2,\n',
        '           label=f"median={np.median(bvals):.0f}")\n',
        'ax.legend(fontsize=9)\n',
        '\n',
        'ax = axes[1]\n',
        'ax.hist(sc, bins=40, color="#ED7D31", edgecolor="white", linewidth=.3)\n',
        'ax.set_xlabel("Slice coverage (max backward / n_stmts)")\n',
        'ax.set_ylabel("Count")\n',
        'ax.set_title("Slice Coverage Distribution")\n',
        'ax.axvline(np.median(sc), color="red", linestyle="--", linewidth=1.2,\n',
        '           label=f"median={np.median(sc):.2f}")\n',
        'ax.legend(fontsize=9)\n',
        '\n',
        'ax = axes[2]\n',
        'ax.scatter(mb, mf, alpha=0.35, s=8, color="#70AD47")\n',
        'ax.set_xlabel("Max backward-slice size")\n',
        'ax.set_ylabel("Max forward-slice size")\n',
        'ax.set_title("Backward vs Forward Slice Size")\n',
        '\n',
        'plt.tight_layout(); plt.show()\n',
    ]),

    code('a700b005', [
        '# Fig 2: slice coverage CDF + top-20 methods by max backward slice\n',
        'fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n',
        '\n',
        'ax = axes[0]\n',
        'sorted_sc = sorted(sc)\n',
        'y_vals = [i/len(sorted_sc) for i in range(len(sorted_sc))]\n',
        'ax.plot(sorted_sc, y_vals, color="#4472C4", linewidth=1.5)\n',
        'ax.axvline(0.5, color="grey", linestyle=":", linewidth=1)\n',
        'ax.axhline(0.5, color="grey", linestyle=":", linewidth=1)\n',
        'ax.set_xlabel("Slice coverage (max backward / n_stmts)")\n',
        'ax.set_ylabel("CDF"); ax.set_title("Slice Coverage CDF")\n',
        '\n',
        'ax = axes[1]\n',
        'top20 = sorted(slice_rows, key=lambda r: -r["max_backward_slice"])[:20]\n',
        'labels = [f"{r[\'class\']}.{r[\'method\']}"[-30:] for r in top20]\n',
        'vals   = [r["max_backward_slice"] for r in top20]\n',
        'colors = ["#C00000" if r["slice_coverage"] > 0.7 else "#4472C4" for r in top20]\n',
        'ax.barh(range(len(vals)), vals, color=colors)\n',
        'ax.set_yticks(range(len(vals)))\n',
        'ax.set_yticklabels(labels, fontsize=7)\n',
        'ax.set_xlabel("Max backward-slice size")\n',
        'ax.set_title("Top 20 Methods by Max Backward Slice\\n(red = coverage > 70%)")\n',
        'ax.invert_yaxis()\n',
        'plt.tight_layout(); plt.show()\n',
    ]),

    code('a700b006', [
        '# Fig 3: backward slice size vs method size, coloured by coverage\n',
        'xs = [r["n_stmt_nodes"]        for r in slice_rows]\n',
        'ys = [r["max_backward_slice"]  for r in slice_rows]\n',
        'cs = [r["slice_coverage"]      for r in slice_rows]\n',
        '\n',
        'fig, ax = plt.subplots(figsize=(8, 5))\n',
        'sc_plot = ax.scatter(xs, ys, c=cs, cmap="RdYlGn_r",\n',
        '                     alpha=0.5, s=10, vmin=0, vmax=1)\n',
        'ax.plot([0, max(xs)], [0, max(xs)], "k--", linewidth=0.8,\n',
        '        label="slice = method size")\n',
        'plt.colorbar(sc_plot, ax=ax, label="slice coverage")\n',
        'ax.set_xlabel("Method size (statement nodes)")\n',
        'ax.set_ylabel("Max backward-slice size")\n',
        'ax.set_title("Backward Slice Size vs Method Size (color = coverage)")\n',
        'ax.legend(fontsize=9)\n',
        'plt.tight_layout(); plt.show()\n',
    ]),

    code('a700b007', [
        '# Load example slice graphs\n',
        'slice_graphs = {}  # sanitized_mid -> (G, entry, criterion, bslice_set)\n',
        'for pkl in sorted(EX7.glob("*.pkl")):\n',
        '    try:\n',
        '        G, entry, crit, bslice = pickle.loads(pkl.read_bytes())\n',
        '        slice_graphs[pkl.stem] = (G, entry, crit, bslice)\n',
        '    except Exception as e:\n',
        '        print(f"Could not load {pkl.name}: {e}")\n',
        '\n',
        'print(f"Example slice graphs loaded: {len(slice_graphs)}")\n',
        'for k, (G, entry, crit, bslice) in slice_graphs.items():\n',
        '    print(f"  {k[:55]}  nodes={G.number_of_nodes()}  "\n',
        '          f"edges={G.number_of_edges()}  bslice={len(bslice)}")\n',
    ]),

    code('a700b008', [
        '# Fig 4: PDG with backward slice highlighted\n',
        'if not slice_graphs:\n',
        '    print("No example graphs — run build_slice_features.py first")\n',
        'else:\n',
        '    best_key = max(slice_graphs, key=lambda k: len(slice_graphs[k][3]))\n',
        '    G_ex, entry_ex, crit_ex, bslice_ex = slice_graphs[best_key]\n',
        '\n',
        '    try:\n',
        '        pos = nx.nx_agraph.graphviz_layout(G_ex, prog="dot")\n',
        '    except Exception:\n',
        '        pos = nx.spring_layout(G_ex, seed=42, k=1.8)\n',
        '\n',
        '    fig, ax = plt.subplots(figsize=(12, 8))\n',
        '    node_list = list(G_ex.nodes())\n',
        '    node_color = []\n',
        '    for n in node_list:\n',
        '        if n == crit_ex:\n',
        '            node_color.append("#C00000")\n',
        '        elif n in set(bslice_ex):\n',
        '            node_color.append("#FF9999")\n',
        '        elif G_ex.nodes[n].get("kind") == "ENTRY":\n',
        '            node_color.append("#70AD47")\n',
        '        else:\n',
        '            node_color.append("#BDD7EE")\n',
        '\n',
        '    nx.draw_networkx_nodes(G_ex, pos, nodelist=node_list,\n',
        '                           node_color=node_color, node_size=500, ax=ax)\n',
        '\n',
        '    cdg = [(u,v) for u,v,d in G_ex.edges(data=True) if d.get("layer")=="cdg"]\n',
        '    ddg = [(u,v) for u,v,d in G_ex.edges(data=True) if d.get("layer")=="ddg"]\n',
        '    cfg = [(u,v) for u,v,d in G_ex.edges(data=True) if d.get("layer")=="cfg"]\n',
        '\n',
        '    nx.draw_networkx_edges(G_ex, pos, edgelist=cfg, ax=ax,\n',
        '                           edge_color="#CCCCCC", alpha=0.5,\n',
        '                           connectionstyle="arc3,rad=0.05", arrows=True, arrowsize=8)\n',
        '    nx.draw_networkx_edges(G_ex, pos, edgelist=cdg, ax=ax,\n',
        '                           edge_color="#999999", style="dashed",\n',
        '                           connectionstyle="arc3,rad=0.12", arrows=True, arrowsize=12)\n',
        '    nx.draw_networkx_edges(G_ex, pos, edgelist=ddg, ax=ax,\n',
        '                           edge_color="#4472C4",\n',
        '                           connectionstyle="arc3,rad=-0.12", arrows=True, arrowsize=12)\n',
        '\n',
        '    labels = {n: G_ex.nodes[n].get("label", n)[:18] for n in G_ex.nodes()}\n',
        '    nx.draw_networkx_labels(G_ex, pos, labels=labels, font_size=6, ax=ax)\n',
        '\n',
        '    from matplotlib.patches import Patch\n',
        '    ax.legend(handles=[\n',
        '        Patch(color="#C00000", label="Criterion (largest backward slice)"),\n',
        '        Patch(color="#FF9999", label="In backward slice"),\n',
        '        Patch(color="#BDD7EE", label="Not in slice"),\n',
        '        Patch(color="#70AD47", label="Entry"),\n',
        '    ], loc="lower right", fontsize=8)\n',
        '    ax.set_title(\n',
        '        f"PDG — backward slice highlighted | "\n',
        '        f"slice={len(bslice_ex)} of {G_ex.number_of_nodes()} nodes\\n"\n',
        '        f"CDG=dashed-grey  DDG=blue  CFG=light-grey", fontsize=10)\n',
        '    plt.tight_layout(); plt.show()\n',
    ]),

    code('a700b009', [
        '# Slice stats by method kind\n',
        'kind_groups = defaultdict(list)\n',
        'for r in slice_rows:\n',
        '    kind_groups[r["kind"]].append(r)\n',
        '\n',
        'print(f"{\"Kind\":<15} {\"Count\":>6} {\"AvgMaxBSlice\":>14} "\n',
        '      f"{\"AvgCoverage\":>12} {\"AvgRetSlice\":>13}")\n',
        'print("-" * 65)\n',
        'for knd, rows in sorted(kind_groups.items()):\n',
        '    amb  = sum(r["max_backward_slice"] for r in rows) / len(rows)\n',
        '    acov = sum(r["slice_coverage"]     for r in rows) / len(rows)\n',
        '    ars  = sum(r["return_slice_size"]  for r in rows) / len(rows)\n',
        '    print(f"{knd:<15} {len(rows):>6} {amb:>14.1f} {acov:>12.3f} {ars:>13.1f}")\n',
        '\n',
        'n_nodep = sum(1 for r in slice_rows if r["n_dep_edges"] == 0)\n',
        'print(f"\\nMethods with zero dependence edges: "\n',
        '      f"{n_nodep}/{len(slice_rows)} = {n_nodep/len(slice_rows):.1%}")\n',
    ]),

    md('a700b010', [
        '### Family 7 Observations\n',
        '\n',
        'Key findings from the program-slicing analysis of the Apache Groovy base snapshot:\n',
        '\n',
        '- **Slice size distribution**: most per-statement backward slices are small; '
        'trivial (single-statement) methods have coverage = 1.0, while complex methods '
        'show slices covering 40-80% of the body\n',
        '- **Return-slice size**: the backward slice of return statements reveals how much '
        'state must be computed before output — a proxy for output complexity\n',
        '- **High-influence statements**: forward-slice coverage identifies statements '
        'whose values propagate widely (e.g. parameter assignments near method entry)\n',
        '- **Coverage vs method size**: slice coverage tends to decrease with method size '
        'as not all sub-computations are reachable from any single criterion\n',
        '- Methods with zero dependence edges are trivially simple; their slices are '
        'always size 1\n',
    ]),

]

nb['cells'].extend(new_cells)
nb_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print(f'Done. Total cells: {len(nb["cells"])}')
print('Cells added:', [c["id"] for c in new_cells])
