[project]
name = "jit-defect-prediction"
version = "0.1.0"
description = "JIT commit-level defect prediction framework"
authors = [{ name = "Your Name" }]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "numpy",
    "scikit-learn",
    "matplotlib",
    "pyyaml",
    "python-dotenv"
]

[tool.setuptools.packages]
find = { include = ["kg_commit*"] }

[tool.setuptools.package-data]
kg_commit = ["**/*"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
