"""
Render the scalability / complexity LaTeX tables into outputs/scalability/*.tex
from the E1-E5 JSON. booktabs style, leading-zero-stripped decimals, matching the
existing v4 tables (tab_layers / tab_paper_groovy). The paper \input{}s these.

Tables:
  tab_kg_profile.tex          per-layer size profile incl. CSTG + power-law tail
  tab_growth.tex              per-layer growth, churn, buggy/benign size + sig.
  tab_build_complexity.tex    sampled parse+diff cost + O(change) fit R^2
  tab_prediction_latency.tex  per-method predict latency across the graph family
  tab_significance.tex        richness / method / fusion significance (Holm p)

Run:  python scalability/make_scalability_tables.py
"""
import json
import numpy as np

import _common as C


def _load(name):
    p = C.OUT / name
    return json.load(open(p)) if p.exists() else None


def z(x, nd=3):
    """Leading-zero-stripped decimal (0.615 -> .615), matching the v4 tables."""
    if x is None or (isinstance(x, float) and (np.isnan(x) or np.isinf(x))):
        return "--"
    s = f"{x:.{nd}f}"
    return s[1:] if s.startswith("0.") else (s[2:] if s.startswith("-0.") and False else s)


def num(x):
    return f"{int(round(x)):,}".replace(",", "{,}")


def write(name, body):
    # canonical copy under outputs/scalability, and a copy under
    # docs/figures/v4/scalability so the paper can \input{figures/v4/scalability/...}
    # (relative to docs/, matching the existing v4 table convention).
    C.OUT.mkdir(parents=True, exist_ok=True)
    (C.OUT / name).write_text(body, encoding="utf-8")
    C.FIG.mkdir(parents=True, exist_ok=True)
    (C.FIG / name).write_text(body, encoding="utf-8")
    print(f"  {name}")


# ── T1 : KG size profile ────────────────────────────────────────────────────

def tab_kg_profile(prof):
    if not prof:
        return
    rows = []
    for vid in ["ast", "cfg", "dfg", "pdg", "seq"]:
        r = prof.get(vid)
        if not r:
            continue
        pl = r.get("delta_per_commit_powerlaw", {})
        rows.append(
            f"{r['pretty']} & {num(r['nodes'])} & {num(r['delta_total'])} & "
            f"{r['n_node_types']} & {r['n_token_types']} & "
            f"{num(r['per_file_nodes']['p50'])} & {z(r['per_file_nodes']['gini'],2)} & "
            f"{z(pl.get('alpha', float('nan')),2)} \\\\")
    cstg = prof.get("cstg", {})
    cstg_row = (f"CSTG & {num(cstg.get('n_Term',0))} & "
                f"{num(cstg.get('e_MENTIONS',0)+cstg.get('e_COOCCURS',0)+cstg.get('e_GROUNDS_IN',0))} "
                f"& {cstg.get('n_Term_kinds','--')} & -- & -- & -- & -- \\\\")
    body = r"""% Auto-generated by scalability/make_scalability_tables.py -- do not edit by hand.
\begin{table}[t]
\centering
\caption{Statistical profile of each materialised layer of the final knowledge
graph (Groovy, $8{,}059$ commits). \emph{Med.\ nodes/file} and \emph{Gini} describe
the per-file size distribution; $\alpha$ is the MLE power-law exponent of the
per-commit change-token degree (heavy-tailed for $2<\alpha<3$). The CSTG row counts
its \node{Term} nodes and its semantic edges (\edge{MENTIONS}$+$\edge{COOCCURS}$+$\edge{GROUNDS\_IN}).}
\label{tab:scal-profile}
\begin{tabular}{lrrrrrrr}
\toprule
Layer & Nodes & Delta-edges & Node & Token & Med.\ nodes & Gini & $\alpha$ \\
      &       &             & types & types & /file       &      &          \\
\midrule
""" + "\n".join(rows) + "\n\\midrule\n" + cstg_row + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_kg_profile.tex", body)


# ── T2 : growth & modification ──────────────────────────────────────────────

def tab_growth(growth):
    if not growth:
        return
    rows = []
    for vid in ["ast", "cfg", "dfg", "pdg", "seq"]:
        r = growth.get(vid)
        if not r:
            continue
        bb = r["buggy_vs_benign"]; ratio = bb["mean_size_ratio"]
        rows.append(
            f"{vid.upper()} & {num(r['total_delta_edges'])} & "
            f"{z(r['churn_ratio'],2)} & {num(r['delta_per_commit']['p50'])} & "
            f"{num(r['delta_per_buggy']['mean'])} & {num(r['delta_per_benign']['mean'])} & "
            f"{z(ratio['ratio'],2)} [{z(ratio['lo'],2)},{z(ratio['hi'],2)}] & "
            f"{_p(bb['mannwhitney_p'])} \\\\")
    body = r"""% Auto-generated -- do not edit by hand.
\begin{table}[t]
\centering
\caption{Per-commit growth and modification statistics recovered from the online
delta stream. \emph{Churn} is \edge{REMOVES}/\edge{ADDS}; buggy/benign columns are
mean per-commit delta-edges; the ratio carries a bootstrap $95\%$ CI and a
Mann--Whitney $U$ $p$-value for the (buggy $>$ benign) size separation.}
\label{tab:scal-growth}
\begin{tabular}{lrrrrrl}
\toprule
Layer & Total & Churn & Med.\ & Buggy & Benign & Ratio [CI] \quad ($p$) \\
      & delta & & /commit & mean & mean & \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_growth.tex", body)


def _p(p):
    if p is None or np.isnan(p):
        return "--"
    if p < 1e-99:
        return "$<$1e-99"
    return f"{p:.0e}".replace("e-0", "e-")


# ── T3 : build complexity ───────────────────────────────────────────────────

def tab_build_complexity(build):
    if not build:
        return
    rows = []
    for vid in ["ast", "cfg", "dfg", "pdg", "seq"]:
        r = build.get(vid)
        if not r or "ms_per_file" not in r:
            continue
        fn = r["fit_vs_nodes_after"]; fd = r["fit_vs_delta_size"]
        ex = r.get("extrapolation", {})
        rows.append(
            f"{vid.upper()} & {r['n']} & {z(r['ms_per_file']['p50'],1)} & "
            f"{z(fn['r2'],2)} & {z(fd['r2'],2)} & "
            f"{z(ex.get('est_total_seconds',0)/60.0,1)} \\\\")
    body = r"""% Auto-generated -- do not edit by hand.
\begin{table}[t]
\centering
\caption{Build/modify cost from a sampled replay of the real parse+diff work
(CPU only; Neo4j write I/O excluded). The high $R^2$ of the time-vs-change-size fit
confirms per-commit work is \emph{linear in the size of the change} (\,$O(\text{change})$\,),
independent of history length. The last column extrapolates the median per-file cost
to the full stream.}
\label{tab:scal-build}
\begin{tabular}{lrrrrr}
\toprule
Layer & \#samp. & Med.\ ms & $R^2$ (nodes) & $R^2$ (delta) & Est.\ total (min) \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_build_complexity.tex", body)


# ── T4 : prediction latency ─────────────────────────────────────────────────

def tab_prediction_latency(lat):
    if not lat:
        return
    graphs = [g for g in C.FINAL_GRAPHS if g in lat]
    rows = []
    for m in C.FINAL_METHODS:
        cells = " & ".join(z(lat[g]["predict_ms_per_commit"][m]["median"], 3)
                           for g in graphs)
        rows.append(f"{m} & {cells} \\\\")
    dep = " & ".join(z(lat[g]["deployed_F_predict_ms_per_commit"], 3) for g in graphs)
    cols = "l" + "r" * len(graphs)
    head = " & ".join(C.GRAPH_NAME[g].replace("Core+", "+") for g in graphs)
    body = r"""% Auto-generated -- do not edit by hand.
\begin{table}[t]
\centering
\caption{Prediction latency (median ms per commit) of the five final graph-inference
methods across the graph family, at deployment (steady per-commit scoring from
strictly-past state; embedding refit cost is amortised separately). The deployed
graph-native fusion $F=$~RN$+$PPR runs at sub-millisecond per commit even on the
richest final graph.}
\label{tab:scal-latency}
\begin{tabular}{""" + cols + r"""}
\toprule
Method & """ + head + r""" \\
\midrule
""" + "\n".join(rows) + r"""
\midrule
\textbf{$F$=RN+PPR} & """ + dep + r""" \\
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_prediction_latency.tex", body)


# ── T5 : significance ───────────────────────────────────────────────────────

def tab_significance(sig):
    if not sig:
        return
    rich_rows, ppr_rows, fus_rows = [], [], []
    rich = sig.get("richness_vs_core", {})
    for k, v in rich.items():
        if "final>Core" in k:
            m = k.split(":")[0]
            d = v["auc_a"] - v["auc_b"]
            rich_rows.append(f"{m}: final $>$ Core & {z(d,3)} & "
                             f"{_p(v.get('p_holm', v['p']))} \\\\")
    mc = sig.get("ppr_vs_others_final", {})
    for k, v in mc.items():
        d = v["roc_delong"]
        other = k.replace("PPR>", "").replace(" (final)", "")
        ppr_rows.append(f"PPR $>$ {other} & {z(d['auc_a']-d['auc_b'],3)} & "
                        f"{_p(d.get('p_holm', d['p']))} \\\\")
    # Deployed-model semantic effect: authoritative F vs F+G from the fusion run.
    ff = _final_fusion_delta()
    if ff:
        for metric, (f, fg) in ff.items():
            fus_rows.append(f"F+G $>$ F ({metric}) & {z(fg-f,3)} & "
                            f"{z(f,3)}$\\to${z(fg,3)} \\\\")

    body = r"""% Auto-generated -- do not edit by hand.
\begin{table}[t]
\centering
\caption{Statistical significance of the headline V4 comparisons. Rows in the
first two blocks use paired per-commit out-of-sample scores: $\Delta$AUC is the
ROC-AUC difference and $p$ is DeLong's paired test, Holm-corrected within each
block. The last block reports the deployed semantic-channel effect (F$+$G vs.\ F)
as the change in each headline metric from the final fusion run
(\code{run\_final\_fusion.py}).}
\label{tab:scal-sig}
\begin{tabular}{lrl}
\toprule
Comparison & $\Delta$ & $p$ (Holm) / value \\
\midrule
\multicolumn{3}{@{}l}{\textit{Graph richness helps (final graph vs.\ Core), $\Delta$AUC}}\\
""" + "\n".join(rich_rows) + r"""
\midrule
\multicolumn{3}{@{}l}{\textit{Best method on the final graph, $\Delta$AUC}}\\
""" + "\n".join(ppr_rows) + r"""
\midrule
\multicolumn{3}{@{}l}{\textit{Deployed semantic channel F$+$G vs.\ F}}\\
""" + "\n".join(fus_rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_significance.tex", body)


def tab_cstg_ablation(abl):
    if not abl:
        return
    comp = abl["components"]
    meta = abl["_meta"]

    def row(k):
        c = comp[k]
        return (f"{c['pretty']} & {z(c['ROC'])} & {z(c['PR'])} & {z(c['F1'])} & "
               f"{z(c['Popt'])} & {z(c['ACC20'])} \\\\")

    rf_rows = [row(k) for k in ("plain_tfidf_RF", "tw_idf_RF", "cstg_full_RF",
                                "jit_cstg_full_RF")]
    lr_rows = [row(k) for k in ("plain_tfidf_LR", "tw_idf_LR", "prior_LR",
                                "tw_idf_prior_LR", "cstg_full_LR")]
    pb = meta["published_baseline_RF"]
    body = r"""% Auto-generated -- do not edit by hand.
\begin{table}[t]
\centering
\caption{CSTG internal-layer ablation on the controlled split (train first
$70\%$, test last $15\%$; test bug rate $""" + f"{meta['test_bug_rate']:.3f}" + r"""$).
\textbf{Top block (matched RF learner):} the fair, same-learner comparison this
section's Q4 discussion calls for --- plain TF-IDF vs.\ the graph-of-words (TW-IDF)
representation vs.\ the full CSTG, all under Random Forest. \textbf{Bottom block
(balanced LR):} the original component-isolation ablation, showing each piece's
\emph{marginal} contribution under a linear model. Popt/ACC@20 are effort-aware
metrics (\texttt{effort\_metrics.py}).}
\label{tab:cstg-ablation}
\begin{tabular}{@{}lrrrrr@{}}
\toprule
\textbf{Component} & \textbf{ROC} & \textbf{PR} & \textbf{F1} & \textbf{$P_{\mathrm{opt}}$} & \textbf{ACC@20}\\
\midrule
\multicolumn{6}{@{}l}{\textit{Matched-learner comparison (Random Forest)}}\\
""" + "\n".join(rf_rows) + r"""
\midrule
\multicolumn{6}{@{}l}{\textit{Component isolation (balanced Logistic Regression)}}\\
""" + "\n".join(lr_rows) + r"""
\midrule
\textit{published diff-text TF-IDF-768D RF (external baseline)} & \textit{""" + \
        f"{pb['ROC']}" + r"""} & --- & \textit{""" + f"{pb['F1']}" + r"""} & --- & ---\\
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_cstg_ablation.tex", body)


def tab_cstg_graph_ablation(ga):
    """The online graph-inference ablation over separated CSTG hub-graph layers:
    5 methods x 5 variants, one block per headline metric, + the G channel row."""
    if not ga:
        return
    meta = ga["_meta"]
    variants = meta["variants"]
    vnames = {"core": "Core", "mentions": "+MENT.", "twidf": "+TW-IDF",
              "cooccurs": "+COOCC.", "full": "Full"}
    methods = meta["methods"]
    # one block per metric (Buggy-F1, Macro-F1, G-Mean, AUC, MCC) -- the 5 most
    # informative of the 7; Precision/Recall are summarised in the notebook.
    blocks = [("Buggy_F1", "Buggy-F1"), ("Macro_F1", "Macro-F1"),
              ("G_Mean", "G-Mean"), ("AUC", "AUC"), ("MCC", "MCC")]
    col_head = " & ".join(vnames[v] for v in variants)
    lines = []
    for key, pretty in blocks:
        lines.append(r"\multicolumn{" + str(len(variants) + 1) +
                     r"}{@{}l}{\textit{" + pretty + r"}}\\")
        for m in methods:
            cells = " & ".join(z(ga[v]["methods"][m][key], 3) for v in variants)
            lines.append(f"{m} & {cells} \\\\")
        # G channel is graph-independent: show as a single reference value
        if "G_channel" in ga:
            lines.append(r"\;\;G (feature clf.) & \multicolumn{" + str(len(variants)) +
                         r"}{c}{" + z(ga["G_channel"][key], 3) + r"} \\")
        lines.append(r"\midrule")
    if lines and lines[-1] == r"\midrule":
        lines.pop()                              # no rule directly before \bottomrule
    body = r"""% Auto-generated -- do not edit by hand.
\begin{table}[t]
\centering
\caption{CSTG \emph{online graph} ablation: the five final graph-inference methods
(RN, PPR, LP, DW, KGE) run fully online (prequential) over the CSTG's own graph
structure, one column per \emph{separated} CSTG hub-graph layer and one for the
full CSTG --- Core (file/dev hubs only), $+$MENTIONS (unweighted term hubs),
$+$TW-IDF (TextRank-weighted term hubs), $+$COOCCURS (adds the NPMI term--term
graph so walks diffuse through it), and Full CSTG (adds term-kind-typed edges).
The \emph{G (feature clf.)} row is the graph-independent CSTG feature classifier
under the same online protocol, for reference. All seven metrics are computed by
\texttt{online\_jit.final\_metrics}; five are shown here
(\texttt{scalability/cstg\_online\_graph\_ablation.py}).}
\label{tab:cstg-graph-ablation}
\begin{tabular}{@{}l""" + "r" * len(variants) + r"""@{}}
\toprule
Method & """ + col_head + r""" \\
\midrule
""" + "\n".join(lines) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("tab_cstg_graph_ablation.tex", body)


def _final_fusion_delta():
    """Authoritative F vs F+G headline metrics from the final fusion run."""
    import pickle
    p = C.ROOT / "outputs" / "final_fusion_results.pkl"
    if not p.exists():
        return None
    d = pickle.load(open(p, "rb"))
    try:
        F = d["part2"]["F"]["metrics"]; FG = d["part2"]["F+G"]["metrics"]
    except Exception:
        return None
    keys = [("ROC-AUC", "ROC_AUC"), ("PR-AUC", "PR_AUC"),
            ("Macro-F1", "Macro_F1"), ("G-Mean", "G_Mean")]
    return {name: (F[k], FG[k]) for name, k in keys if k in F and k in FG}


def main():
    print("rendering tables ->", C.OUT)
    tab_kg_profile(_load("kg_profile.json"))
    tab_growth(_load("growth.json"))
    tab_build_complexity(_load("build_complexity.json"))
    tab_prediction_latency(_load("prediction_latency.json"))
    tab_significance(_load("significance.json"))
    tab_cstg_ablation(_load("cstg_ablation.json"))
    tab_cstg_graph_ablation(_load("cstg_graph_ablation.json"))
    print("done.")


if __name__ == "__main__":
    main()
